name: Generate Podcast Feeds

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10  # Update the Python version here

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml

    - name: Run script
      run: python feed.py

    - name: Check for changes
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        if git diff --quiet; then
          echo "No changes to commit"
        else
          git add .
          git commit -m "Modified Feed"
          git push
        fi
